// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upzbauplibbnmmsvlsjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwemJhdXBsaWJibm1tc3Zsc2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njk3MzksImV4cCI6MjA3MTI0NTczOX0.Dd2bMixDOv4beDu2z00qW7UU0exL__1AEGLGk7zw0Yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});